version: '3.8'

services:
  web:
    build: .
    container_name: test01-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
